#!/usr/bin/env python3
import argparse
import json
import pandas as pd
import numpy as np

def load_genre_map(jsonl_path):
    """
    Creates a mapping from conversation ID to communication genre based on a JSONL file.

    Args:
        jsonl_path (str): Path to the original JSONL file containing metadata.

    Returns:
        dict: A mapping of {conversation_id: communication_genre}.
    """
    genre_map = {}
    with open(jsonl_path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                obj = json.loads(line)
                # Unwrap data if it follows the common {"status":"ok", "data":{...}} pattern
                data_obj = obj["data"] if "data" in obj and isinstance(obj["data"], dict) else obj
                
                cid = data_obj.get("conversation_id") or data_obj.get("id") or data_obj.get("convo_id")
                genre = data_obj.get("communication_genre")
                
                if cid is not None and genre is not None:
                    genre_map[str(cid)] = str(genre)
            except json.JSONDecodeError:
                continue
    return genre_map

def compute_stats(series):
    """
    Computes count and mean for a series of numeric values.

    Args:
        series (pd.Series): A series of potentially numeric values.

    Returns:
        dict: A dictionary containing 'n' (count) and 'mean'.
    """
    s = pd.to_numeric(series, errors='coerce').dropna()
    if len(s) == 0:
        return {"n": 0, "mean": np.nan}
    return {"n": len(s), "mean": s.mean()}

def main():
    """
    Main logic to generate a table of lexical similarities grouped by genre and drift status.
    """
    parser = argparse.ArgumentParser()
    parser.add_argument("--jsonl", required=True, help="Original JSONL file for metadata/genre mapping")
    parser.add_argument("--lexical_csv", required=True, help="Lexical edges CSV generated by lexical_similarity.py")
    parser.add_argument("--out_csv", required=True, help="Output destination for the genre-lexical table")
    args = parser.parse_args()

    # 1. Load genre metadata
    print(f"Loading genre metadata from {args.jsonl}...")
    genre_map = load_genre_map(args.jsonl)
    print(f"Mapped {len(genre_map)} conversation IDs.")

    # 2. Load and normalize lexical data
    print(f"Loading lexical metrics from {args.lexical_csv}...")
    df = pd.read_csv(args.lexical_csv)
    
    # Ensure drift is treated as boolean
    if df["drift"].dtype == object:
        df["drift"] = df["drift"].map(lambda x: True if str(x).lower() == "true" else 
                                               (False if str(x).lower() == "false" else np.nan))

    # 3. Associate each edge with its respective genre
    df["conversation_id"] = df["conversation_id"].astype(str)
    df["genre"] = df["conversation_id"].map(genre_map)

    # Filter out records without genre mapping
    num_missing = df["genre"].isna().sum()
    if num_missing > 0:
        print(f"Warning: {num_missing} edges had no matching genre and will be excluded.")
        df = df.dropna(subset=["genre"])

    # 4. Aggregate metrics by Genre and Drift type
    metrics = ["rouge_l_f1", "jaccard_unigram"]
    if "jaccard_bigram" in df.columns:
        metrics.append("jaccard_bigram")

    grouped_results = []
    
    # Process each unique genre found
    unique_genres = sorted(df["genre"].unique())
    for g in unique_genres:
        for drift_val, label in [(False, "Within (Drift=False)"), (True, "Boundary (Drift=True)")]:
            subset = df[(df["genre"] == g) & (df["drift"] == drift_val)]
            row = {"Genre": g, "Type": label}
            
            for m in metrics:
                s = compute_stats(subset[m])
                row[f"{m}_n"] = s["n"]
                row[f"{m}_mean"] = s["mean"]
            
            grouped_results.append(row)

    # 5. Append global "Overall" statistics
    for drift_val, label in [(False, "Within (Drift=False)"), (True, "Boundary (Drift=True)")]:
        subset = df[df["drift"] == drift_val]
        row = {"Genre": "Overall", "Type": label}
        
        for m in metrics:
            s = compute_stats(subset[m])
            row[f"{m}_n"] = s["n"]
            row[f"{m}_mean"] = s["mean"]
        
        grouped_results.append(row)

    # 6. Finalize DataFrame and Export
    res_df = pd.DataFrame(grouped_results)
    
    # Define and order columns
    ordered_cols = ["Genre", "Type"]
    for m in metrics:
        ordered_cols.extend([f"{m}_n", f"{m}_mean"])
        
    res_df = res_df[ordered_cols]
    
    print(f"Exporting genre-wise lexical table to {args.out_csv}...")
    res_df.to_csv(args.out_csv, index=False)
    
    print("\n=== Genre-wise Lexical Similarity Preview ===")
    print(res_df.to_string(index=False))

if __name__ == "__main__":
    main()
